ML_SITE_ID = "MLC"
ML_VEHICLE_DOMAIN_ID = "MLC-CARS_AND_VANS_FOR_COMPATIBILITIES"

ATTR_BRAND = "BRAND"
ATTR_MODEL = "CAR_AND_VAN_MODEL"
ATTR_YEAR = "YEAR"
ATTR_VERSION = "CAR_AND_VAN_SUBMODEL"
ATTR_ENGINE = "CAR_AND_VAN_ENGINE"
ATTR_TRANSMISSION = "TRANSMISSION_CONTROL_TYPE"

SEARCH_STATUS_PENDING = "PENDING"
SEARCH_STATUS_RESOLVED = "RESOLVED"
SEARCH_STATUS_NOT_FOUND = "NOT_FOUND"
SEARCH_STATUS_AMBIGUOUS = "AMBIGUOUS"
SEARCH_STATUS_ERROR = "ERROR"

PUBLISH_STATUS_NOT_SENT = "NOT_SENT"
PUBLISH_STATUS_SENT = "SENT"
PUBLISH_STATUS_FAILED = "FAILED"