"""create informed_non_compatible_mlc table

Revision ID: 4af8fad82ebe
Revises: 
Create Date: 2026-03-22 23:00:58.348311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4af8fad82ebe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('informed_non_compatible_mlc',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mlc', sa.String(length=30), nullable=False),
    sa.Column('informed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mlc', name='uq_informed_non_compatible_mlc_mlc')
    )
    op.create_index(op.f('ix_informed_non_compatible_mlc_mlc'), 'informed_non_compatible_mlc', ['mlc'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_informed_non_compatible_mlc_mlc'), table_name='informed_non_compatible_mlc')
    op.drop_table('informed_non_compatible_mlc')
    # ### end Alembic commands ###
