"""add has_exception to informed_non_compatible_mlc

Revision ID: 7c619132cb12
Revises: 4af8fad82ebe
Create Date: 2026-03-23 00:35:49.913445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c619132cb12'
down_revision: Union[str, Sequence[str], None] = '4af8fad82ebe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('informed_non_compatible_mlc', sa.Column('has_exception', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_informed_non_compatible_mlc_has_exception'), 'informed_non_compatible_mlc', ['has_exception'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_informed_non_compatible_mlc_has_exception'), table_name='informed_non_compatible_mlc')
    op.drop_column('informed_non_compatible_mlc', 'has_exception')
    # ### end Alembic commands ###
